baseURL = "http://www.dengesolar.com/"
languageCode = "en-us"
title = "DengeSolar - Yenilenebilir Enerji Çözümleri"
theme = "dersan-hugo-modern-business"

[params]
    description = "Güneş Enerjisi, Güneş Panelleri, Solar Panel, Yenilenebilir Enerji, Rüzgar Enerjisi"
    author = "DengeSolar"
    card01header = "Güneş Enerjisi"
    card01text = "Güneş enerjisi çözümleri"
    card02header = "Rüzgar Enerjisi"
    card02text = "Rüzgar enerjisi projeleri"
    card03header = "Otomasyon ve Yazılım"
    card03text = "Otomasyon, robotik, yazılım, entegrasyon projeleri"
    contactustext = "Lorex ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi."
