baseURL = "http://example.org/"
languageCode = "en-us"
title = "DengeSolar - Yenilenebilir Enerji Çözümleri"
theme = "dersan-hugo-modern-business"

[params]
  description = "Güneş Enerjisi, Güneş Panelleri, Solar Panel, Yenilenebilir Enerji, Rüzgar Enerjisi"
  author = "DengeSolar"